[package]
name = "rustic_scheduler"
version = "0.1.0"
categories = ["command-line-utilities"]
edition = "2021"
homepage = "https://rustic.cli.rs/"
keywords = [
  "backup",
  "restic",
  "deduplication",
  "encryption",
  "cli",
  "scheduler",
]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/rustic-rs/rustic_scheduler"
description = """
rustic scheduler - a client/server application to schedule regular backups on
many clients to one identical repository controlled by a central scheduling
server.
"""

[[bin]]
name = "rustic-scheduler-server"
path = "src/bin/rustic-scheduler-server.rs"

[[bin]]
name = "rustic-scheduler-client"
path = "src/bin/rustic-scheduler-client.rs"

[dependencies]
anyhow = "1"
axum = { version = "0.6.20", features = ["ws"] }
chrono = "0.4.30"
clap = "4"
clap_derive = "4.4.2"
cron = "0.12"
env_logger = "0.10"
gethostname = "0.4.3"
log = "0.4.20"
rustic_core = { git = "https://github.com/rustic-rs/rustic", version = "0" }
serde = "1"
serde_derive = "1.0.188"
serde_json = "1"
serde_with = "3"
tokio = { version = "1", features = ["full"] }
toml = "0.7.8"
tungstenite = "0.20"
url = "2.4"
