[package]
name = "rustic_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
rustic_core = { path = "../rustic/crates/rustic_core/", version = "0" }
env_logger = "0.10"
tungstenite = "0.20"
url = "2.4"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
anyhow = "1"
cron = "0.12"
chrono = "0.4.26"
log = "0.4.20"
toml = "0.7.6"
clap = { version = "4", features = ["derive"] }
axum = {version = "0.6.20", features = ["ws"] }
gethostname = "0.4.3"
serde_with = "3"
tokio = "1"
