name: Check release

on:
  push:
    branches:
      - "release/**"
  # TODO!: We might want to do it manually? Not sure.
  # workflow_dispatch:
  #   inputs:
  #     crate:
  #       description: Crate to release
  #       required: true
  #       type: choice
  #       options:
  #         - rustic_scheduler

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  determine-package:
    name: Determine package to release
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.determine-package-name.outputs.package }}
    steps:
      - name: Determine package
        id: determine-package-name
        run: |
          if [[ ${{ github.ref }} == *"rustic_scheduler"* ]]; then
          echo "package=rustic_scheduler" >> $GITHUB_OUTPUT
          fi

  breaking-cli:
    name: Check breaking CLI changes
    runs-on: ${{ matrix.job.os }}
    needs: determine-package
    if: needs.determine-package.outputs.package == 'rustic_scheduler'
    strategy:
      matrix:
        rust: [stable]
        job:
          # - os: macos-latest # TODO: Need to generate fixtures for macOS first
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2
      - name: Run Cargo Test
        run: cargo test -r --all-targets --all-features --workspace -p ${{ needs.determine-package.outputs.package }} -- --ignored

  semver-check:
    name: Check SemVer
    runs-on: ubuntu-latest
    needs: determine-package
    strategy:
      matrix:
        rust: [stable]
        job:
          - os: ubuntu-latest
          # - os: windows-latest # Panics
          # - os: macos-latest # Panics
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@e275dda72e250d4df5b564e969e1348d67fefa52 # v2
        with:
          package: ${{ needs.determine-package.outputs.package }}
